### ISSUE TITLE
Rsyslog.s always getting **No Match**

### ISSUE THREAD

**Issue by jithinjks** [asksven/locating-ssh-hackers#1]
Hi ,

# We handle "Invalid user q from xxx.xxx.xxx.xxx port 10664"
template(name="ip-json" type="string" string="{\"username\":\"%msg:R,ERE,1,DFLT:^ Invalid.*user ([a-zA-Z]*).* ([0-9][0-9]*[0-9]*.[0-9][0-9]*[0-9]*.[0-9][0-9]*[0-9]*.[0-9][0-9]*[0-9]*).* port ([0-9]*)--end%\",\"ip\":\"%msg:R,ERE,2,DFLT:^ Invalid.*user ([a-zA-Z]*).* ([0-9][0-9]*[0-9]*.[0-9][0-9]*[0-9]*.[0-9][0-9]*[0-9]*.[0-9][0-9]*[0-9]*).* port ([0-9]*)--end%\",\"port\":\"%msg:R,ERE,3,DFLT:^ Invalid.*user ([a-zA-Z]*).* ([0-9][0-9]*[0-9]*.[0-9][0-9]*[0-9]*.[0-9][0-9]*[0-9]*.[0-9][0-9]*[0-9]*).* port ([0-9]*)--end%\"}")

The above is the copied regex and my ssh log is 

Invalid user ubunt from 111.92.25.118
Aug 19 08:42:07 ip-10-5-1-18 sshd[12300]: input_userauth_request: invalid user ubunt [preauth]
Aug 19 08:42:08 ip-10-5-1-18 sshd[12300]: Connection closed by 111.92.25.118 port 18852 [preauth]

Am always getting **No Match**.

**Comment by asksven** [comment]
Looks like a difference in the logging implementation to me. Could you please provide more log entries?

**Comment by asksven** [comment]
with two occurences there is not much I can do. Please follow the instructions from the blog-post to query and define the regex: https://blog.asksven.io/posts/locating-ssh-hackers/ in paragraph "Find out the log pattern we are looking for"
